declare const IS_DEV: boolean;
declare const SPOON_API_KEY: string;
declare module "./images/*.png";
declare module '@/assets/caruselItems/intolerance.png';
declare module '@/assets/caruselItems/configurator.png';
declare module '@/assets/caruselItems/favourites.png';
declare module '@/assets/caruselItems/recipeList.png';
declare module '@/assets/caruselItems/сusines.png';
declare module '@/assets/caruselItems/history.png';
declare module '@/assets/leo.png';
declare module "@/assets/healthy.svg";
declare module "@/assets/gluten-free.svg";
declare module "@/assets/dairy-free.svg";
declare module "@/assets/vegetarian.svg";
declare module "@/assets/vegetarian.svg";
declare module "@/assets/ovovegetarian.svg";
declare module "@/assets/vegan.svg";
declare module "@/assets/pescetarian.svg";
declare module "@/assets/paleo.svg";
declare module "@/assets/primal.svg";
declare module "@/assets/lowfoodmap.svg";
declare module "@/assets/whole30.svg";