declare const IS_DEV: boolean;
declare const SPOON_API_KEY: string;
declare module "./images/*.png";
declare module "@/assets/caruselItems/ConfiguratorMenu.png";
declare module "@/assets/caruselItems/FavouritePage.png"
declare module "@/assets/caruselItems/HistoryPage.png";
declare module "@/assets/caruselItems/IntoleranceMenu.png";
declare module "@/assets/caruselItems/FindeRecipeExample.png";
declare module "@/assets/caruselItems/CusinesMenu.png";
declare module "@/assets/caruselItems/RecipeIdExample.png";
declare module '@/assets/leo.png';
declare module "@/assets/healthy.svg";
declare module "@/assets/gluten-free.svg";
declare module "@/assets/dairy-free.svg";
declare module "@/assets/vegetarian.svg";
declare module "@/assets/vegetarian.svg";
declare module "@/assets/ovovegetarian.svg";
declare module "@/assets/vegan.svg";
declare module "@/assets/pescetarian.svg";
declare module "@/assets/paleo.svg";
declare module "@/assets/primal.svg";
declare module "@/assets/lowfoodmap.svg";
declare module "@/assets/whole30.svg";